chore(deps): bump com.nimbusds:nimbus-jose-jwt from 10.0.2 to 10.6 (#505)
[//]: # (dependabot-start)
⚠️  **Dependabot is rebasing this PR** ⚠️ 

Rebasing might not happen immediately, so don't worry if this takes some
time.

Note: if you make any changes to this PR yourself, they will take
precedence over the rebase.

---

[//]: # (dependabot-end)

Bumps
[com.nimbusds:nimbus-jose-jwt](https://bitbucket.org/connect2id/nimbus-jose-jwt)
from 10.0.2 to 10.6.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/src/master/CHANGELOG.txt">com.nimbusds:nimbus-jose-jwt's
changelog</a>.</em></p>
<blockquote>
<p>10.0.2 (2025-02-25)
* Updates JSONObjectUtils.parse and JSONArrayUtils.parse to reject JSON
strings with object and array nesting deeper than 255. This is intended
to prevent StackOverflowError's in Gson when a parsed JSON string with
excessive nesting is serialised, for example to log the claims of a
parsed JWT. Note that in Gson the JSON reader is not susceptible to
StackOverflowError's, only the serialisation. The nesting limit of depth
255 is introduced in Gson 2.12.0 (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/583">#583</a>).
* Updates GSon to 2.12.1.</p>
<p>10.1 (2025-04-03)
* Restores module-info.java.
* Adds ExpiredJWTException extends BadJWTException to enable easy
programmatic detection whether a JWT has expired (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/585">#585</a>).
* Adds URLBasedJWKSetSource getJWKSetURL and getResourceRetriever
methods
to ease class extension.</p>
<p>10.2 (2025-04-07)
* Gson is made a direct instead of a shaded dependency to address module
issues introduced in 10.1 (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>).</p>
<p>10.3 (2025-05-09)
* Restores the Gson shading, adding placeholder interfaces to prevent
NoClassDefFoundError occurrences at runtime when the JAR is used on a
module path (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/550">#550</a>).</p>
<p>10.3.1 (2025-07-01)
* OctetKeyPairGenerator with Curve.Ed25519 should use the provided
SecureRandom (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/590">#590</a>).</p>
<p>10.4 (2025-07-19)
* Creates a hierarchy of Option interfaces, extended by JWSSignerOption,
JWEEncrypterOption and JWEDecrypterOption. Intended to provide optional
configuration parameters to RSASSASigner, ECDSASigner, RSADecrypter,
etc.
* Introduces CipherMode implementing JWEEncrypterOption and
JWEDecrypterOption, to specify a preferred JCA Cipher mode, such as
MODE_ENCRYPT / MODE_DECRYPT when the default MODE_WRAP / MODE_UNWRAP is
not supported by the JCA provider (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/576">#576</a>).
* Updates RSAEncrypter and RSADecrypter to support the
JWEEncrypterOption
CipherMode.ENCRYPT_DECRYPT (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/576">#576</a>).
* Factors out OptionUtils.ensureMinRSAPrivateKeySize.
* Deprecates OptionUtils.optionIsPresent.</p>
<p>10.4.1 (2025-08-05)
* Adds &quot;requires java.sql&quot; to module com.nimbusds.jose.jwt
(iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/595">#595</a>).</p>
<p>10.4.2 (2025-08-14)
* Updates GSon to 2.13.1.
* Updates BouncyCastle to 1.81.</p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/c1f3c4441041c0f625c989a6d0a97d77401c033e"><code>c1f3c44</code></a>
[maven-release-plugin] prepare release 10.3</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/93076c13979924630813104bcb50ba7ad853db8a"><code>93076c1</code></a>
[maven-release-plugin] prepare for next development iteration</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/0b56cf0ad81e3924d75390ea66d378f1ded61117"><code>0b56cf0</code></a>
OctetKeyPairGenerator with Curve.Ed25519 should use the provided
SecureRandom...</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/584951f855fd5cbb2e4eef050b1ec17f72dd3743"><code>584951f</code></a>
Adds support for specifying the ScheduledExecutorService-instance in
RefreshA...</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/8c347ff07ae37a76fe1f97402b5332eb7b0f2be0"><code>8c347ff</code></a>
Adds release date for 10.3.1</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/60d821b2620e0ddd306cdc04b6a06b705352eef3"><code>60d821b</code></a>
Migrates to central-publishing-maven-plugin</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/0f3191f547880dbe2745efd00389851046de879f"><code>0f3191f</code></a>
[maven-release-plugin] prepare release 10.3.1</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/63b1101bdd8a87170c5293cc926c12c6ae219242"><code>63b1101</code></a>
[maven-release-plugin] prepare for next development iteration</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/cd1345b1c8e5b8ae91e99e0e9e9d4e21d1a699a1"><code>cd1345b</code></a>
Introduces CipherMode to specify a preferred JCA Cipher mode when the
default...</li>
<li><a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/commits/9799fd54dcaef57a7133e56051614678eb91e60f"><code>9799fd5</code></a>
Fixes compile errors - generics (iss <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/issues/576">#576</a>)</li>
<li>Additional commits viewable in <a
href="https://bitbucket.org/connect2id/nimbus-jose-jwt/branches/compare/10.6..10.0.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=com.nimbusds:nimbus-jose-jwt&package-manager=gradle&previous-version=10.0.2&new-version=10.6)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>